# abc-auth-svc — Unified forward authentication service for ABC Cluster
#
# Single service replacing both:
#   abc-forward-auth-svc (namespace abc-reserved, port 4181) — Nomad token validation
#   abc-auth-svc (namespace default, port 8085)              — MinIO session management
#
# Two auth paths in one process:
#   /verify          — Nomad ACL token → X-Auth-User/Group/Namespace/Policies (backward compat)
#   /validate        — abc_session cookie → Remote-User header (Caddy forward_auth)
#   /auth/login      — MinIO credential login form (browser session)
#   /healthz         — liveness (backward compat)
#   /auth/health     — liveness
#   /slots/claim     — claim an unclaimed pool slot, returns config.yaml
#   /manage/slots/*  — lifecycle management (operator token required)
#
# Runs on port 4181 (same as old abc-forward-auth-svc — no changes needed to
# any existing Traefik/Caddy config that calls /verify on that port).
#
# Prerequisites on aither (handled by scripts/install-pocketbase.sh +
#   scripts/install-auth-svc.sh):
#   - /opt/abc-auth-svc/venv/  Python venv with boto3
#   - /opt/abc-auth-svc/abc-auth-svc.py  service script
#   - /etc/abc-auth-svc/session_secret  (chmod 600, single-line secret)
#   - /etc/abc-auth-svc/pb-admin-password  (chmod 600, PocketBase admin password)
#   - /etc/abc-auth-svc/operator_token  (chmod 600, management API token)
#
# Submit:
#   nomad job run auth/abc-auth-svc.nomad.hcl
#
# After submitting, stop the old jobs if still running:
#   NOMAD_NAMESPACE=abc-reserved nomad job stop -purge abc-forward-auth-svc
#   NOMAD_NAMESPACE=abc-reserved nomad job stop -purge abc-signup-svc

job "abc-auth-svc" {
  datacenters = ["seedling-prod"]
  type        = "service"
  namespace   = "abc-reserved"

  node_pool = "platform"

  constraint {
    attribute = "${node.unique.name}"
    value     = "aither"
  }

  group "auth" {
    count = 1

    restart {
      attempts = 5
      interval = "5m"
      delay    = "15s"
      mode     = "delay"
    }

    task "auth-svc" {
      driver = "raw_exec"

      config {
        command = "/opt/abc-auth-svc/venv/bin/python3"
        args    = ["/opt/abc-auth-svc/abc-auth-svc.py"]
      }

      env {
        MINIO_ENDPOINT      = "http://localhost:9000"
        MINIO_CONSOLE_URL   = "http://localhost:9001"   # MinIO console API for SSO pre-login
        NOMAD_ADDR          = "http://100.70.185.46:4646"
        # API endpoint stamped into rendered config.yaml. Canonical host is
        # api.seedling (2026-06-05); nomad.seedling stays as a working alias.
        CLUSTER_NOMAD_ENDPOINT = "https://api.seedling.abc-cluster.cloud"
        AUTH_SVC_PORT       = "4181"
        AUTH_SVC_BIND       = "0.0.0.0"  # bind on all interfaces so edge Caddy can reach via Tailscale
        SESSION_TTL_SECONDS = "604800"   # 7 days
        # Cross-subdomain cookie: shared across *.seedling.abc-cluster.cloud so a session
        # set on workbench.seedling.* is also readable on grafana.seedling.* etc.
        COOKIE_DOMAIN       = ".seedling.abc-cluster.cloud"
        CLI_TOKEN_TTL       = "60"       # magic-link code TTL in seconds (abc portal open)
        # COOKIE_SECURE: true for TLS-fronted deployments (this one, behind the
        # GCP edge). Set "false" ONLY for air-gapped / plain-HTTP LAN deployments
        # — browsers reject Secure cookies over http:// so SSO would silently
        # fail. See design/exploring/seedling-airgap-lan-deployment-scenario.md.
        COOKIE_SECURE       = "true"

        # Generate once: python3 -c "import secrets; print(secrets.token_hex(32))"
        # Created by scripts/install-auth-svc.sh and stored in
        # /etc/abc-auth-svc/session_secret on aither.
        SESSION_SECRET = "REPLACE_WITH_RANDOM_HEX_SECRET"

        # PocketBase connection (abc-pocketbase Nomad job on loopback)
        POCKETBASE_URL    = "http://127.0.0.1:8091"
        PB_ADMIN_EMAIL    = "abc-auth@abc-cluster.cloud"
        # Read from /etc/abc-auth-svc/pb-admin-password at deploy time.
        # Replace the placeholder with: $(cat /etc/abc-auth-svc/pb-admin-password)
        PB_ADMIN_PASSWORD = "REPLACE_WITH_PB_ADMIN_PASSWORD"

        # Nomad management token — used by /manage/slots/*/rotate and reactivate
        # to create/delete Nomad ACL tokens. Same token as .secrets/nomad-bootstrap-prod.json.
        NOMAD_TOKEN = "REPLACE_WITH_NOMAD_BOOTSTRAP_TOKEN"

        # Operator management API token — required on X-Operator-Token header
        # for all /manage/* endpoints. Generated by install-pocketbase.sh.
        # Replace with: $(cat /etc/abc-auth-svc/operator_token)
        OPERATOR_TOKEN = "REPLACE_WITH_OPERATOR_TOKEN"

        # JupyterHub admin API — used by /workbench/token (abc workbench connect)
        # and to stop a user's server on slot suspension.
        # The token is the 'auth-svc' service token defined in tljh-custom.py's
        # _jh_admin_token. The 'auth-svc' role in tljh-custom.py MUST include the
        # 'tokens' scope (added 2026-06-05) — without it POST /users/<u>/tokens
        # returns 403 "no permissions to generate tokens".
        # Replace with: $(cat /etc/abc-auth-svc/jh-admin-api-token)
        # (install-auth-svc.sh extracts this automatically from tljh-custom.py)
        JUPYTERHUB_API_URL   = "http://127.0.0.1:8000/hub/api"
        JUPYTERHUB_API_TOKEN = "REPLACE_WITH_JH_ADMIN_API_TOKEN"
      }

      resources {
        cpu    = 200   # MHz — handles both MinIO + Nomad validation
        memory = 192   # MB — boto3 + stdlib + concurrent requests
      }

      logs {
        max_files     = 5
        max_file_size = 10  # MB
      }
    }
  }
}
